auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: SOMEWIND
url: http://somewind.github.io
feed: /atom.xml
author_info: <a href="http://somewind.github.io/">SOMEWIND</a>
